//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lottery.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear nueva contraseña.
        /// </summary>
        public static string ChangePasswordButtonCreateNewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordButtonCreateNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña actual.
        /// </summary>
        public static string ChangePasswordLabelCurrentPassword {
            get {
                return ResourceManager.GetString("ChangePasswordLabelCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu contraseña se ha modificado correctamente.
        /// </summary>
        public static string ChangePasswordLabelSuccessfullyChanged {
            get {
                return ResourceManager.GetString("ChangePasswordLabelSuccessfullyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1 Segundo.
        /// </summary>
        public static string CreateLobbyLabelCardDisplayOneSecond {
            get {
                return ResourceManager.GetString("CreateLobbyLabelCardDisplayOneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3 Segundos.
        /// </summary>
        public static string CreateLobbyLabelCardDisplayThreeSeconds {
            get {
                return ResourceManager.GetString("CreateLobbyLabelCardDisplayThreeSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo de aparición de las cartas.
        /// </summary>
        public static string CreateLobbyLabelCardDisplayTime {
            get {
                return ResourceManager.GetString("CreateLobbyLabelCardDisplayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2 Segundos.
        /// </summary>
        public static string CreateLobbyLabelCardDisplayTwoSeconds {
            get {
                return ResourceManager.GetString("CreateLobbyLabelCardDisplayTwoSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen de cartas.
        /// </summary>
        public static string CreateLobbyLabelCardImage {
            get {
                return ResourceManager.GetString("CreateLobbyLabelCardImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Centro.
        /// </summary>
        public static string CreateLobbyLabelGameModeCenter {
            get {
                return ResourceManager.GetString("CreateLobbyLabelGameModeCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esquinas.
        /// </summary>
        public static string CreateLobbyLabelGameModeCorners {
            get {
                return ResourceManager.GetString("CreateLobbyLabelGameModeCorners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diagonales.
        /// </summary>
        public static string CreateLobbyLabelGameModeDiagonals {
            get {
                return ResourceManager.GetString("CreateLobbyLabelGameModeDiagonals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marco.
        /// </summary>
        public static string CreateLobbyLabelGameModeFrame {
            get {
                return ResourceManager.GetString("CreateLobbyLabelGameModeFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mega Lotería.
        /// </summary>
        public static string CreateLobbyLabelGameModeMegaLottery {
            get {
                return ResourceManager.GetString("CreateLobbyLabelGameModeMegaLottery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Normal.
        /// </summary>
        public static string CreateLobbyLabelGameModeStandard {
            get {
                return ResourceManager.GetString("CreateLobbyLabelGameModeStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lotería Injusta.
        /// </summary>
        public static string CreateLobbyLabelGameModeUnfairLottery {
            get {
                return ResourceManager.GetString("CreateLobbyLabelGameModeUnfairLottery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fichas.
        /// </summary>
        public static string CreateLobbyLabelMarkers {
            get {
                return ResourceManager.GetString("CreateLobbyLabelMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frijoles.
        /// </summary>
        public static string CreateLobbyLabelMarkersBeans {
            get {
                return ResourceManager.GetString("CreateLobbyLabelMarkersBeans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Corcholatas.
        /// </summary>
        public static string CreateLobbyLabelMarkersBottleCaps {
            get {
                return ResourceManager.GetString("CreateLobbyLabelMarkersBottleCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monedas.
        /// </summary>
        public static string CreateLobbyLabelMarkersCoins {
            get {
                return ResourceManager.GetString("CreateLobbyLabelMarkersCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maíz.
        /// </summary>
        public static string CreateLobbyLabelMarkersCorn {
            get {
                return ResourceManager.GetString("CreateLobbyLabelMarkersCorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bolitas de Papel.
        /// </summary>
        public static string CreateLobbyLabelMarkersPaperBalls {
            get {
                return ResourceManager.GetString("CreateLobbyLabelMarkersPaperBalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sonido.
        /// </summary>
        public static string CreateLobbyLabelSound {
            get {
                return ResourceManager.GetString("CreateLobbyLabelSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Avatar.
        /// </summary>
        public static string CustomizeProfileButtonChangeAvatar {
            get {
                return ResourceManager.GetString("CustomizeProfileButtonChangeAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Correo.
        /// </summary>
        public static string CustomizeProfileButtonChangeEmail {
            get {
                return ResourceManager.GetString("CustomizeProfileButtonChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Apodo.
        /// </summary>
        public static string CustomizeProfileButtonChangeNickname {
            get {
                return ResourceManager.GetString("CustomizeProfileButtonChangeNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Contraseña.
        /// </summary>
        public static string CustomizeProfileButtonChangePassword {
            get {
                return ResourceManager.GetString("CustomizeProfileButtonChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Foto de Perfil.
        /// </summary>
        public static string CustomizeProfileLabelAvatar {
            get {
                return ResourceManager.GetString("CustomizeProfileLabelAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color de Fondo.
        /// </summary>
        public static string CustomizeProfileLabelBackground {
            get {
                return ResourceManager.GetString("CustomizeProfileLabelBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al presionar “Continuar”, se enviará un código de verificación a la dirección de correo electrónico proporcionada..
        /// </summary>
        public static string CustomizeProfileLabelDescription {
            get {
                return ResourceManager.GetString("CustomizeProfileLabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edita y actualiza la información de tu perfil..
        /// </summary>
        public static string CustomizeProfileLabelEditDetails {
            get {
                return ResourceManager.GetString("CustomizeProfileLabelEditDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu correo electrónico se ha modificado correctamente.
        /// </summary>
        public static string CustomizeProfileLabelEmailUpdated {
            get {
                return ResourceManager.GetString("CustomizeProfileLabelEmailUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva dirección de correo electrónico.
        /// </summary>
        public static string CustomizeProfileLabelNewEmailAddress {
            get {
                return ResourceManager.GetString("CustomizeProfileLabelNewEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos del Perfil.
        /// </summary>
        public static string CustomizeProfileLabelProfileDetails {
            get {
                return ResourceManager.GetString("CustomizeProfileLabelProfileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona tu avatar.
        /// </summary>
        public static string CustomizeProfileLabelSelectAvatar {
            get {
                return ResourceManager.GetString("CustomizeProfileLabelSelectAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Redes Sociales.
        /// </summary>
        public static string CustomizeProfileLabelSocialMedia {
            get {
                return ResourceManager.GetString("CustomizeProfileLabelSocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalizar Perfil.
        /// </summary>
        public static string CustomizeProfileLabelTitle {
            get {
                return ResourceManager.GetString("CustomizeProfileLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar amigo.
        /// </summary>
        public static string DeleteFriendButton {
            get {
                return ResourceManager.GetString("DeleteFriendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de amigos.
        /// </summary>
        public static string FriendsListLabelTitle {
            get {
                return ResourceManager.GetString("FriendsListLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string GlobalButtonAccept {
            get {
                return ResourceManager.GetString("GlobalButtonAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string GlobalButtonBack {
            get {
                return ResourceManager.GetString("GlobalButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string GlobalButtonCancel {
            get {
                return ResourceManager.GetString("GlobalButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar.
        /// </summary>
        public static string GlobalButtonContinue {
            get {
                return ResourceManager.GetString("GlobalButtonContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Sala.
        /// </summary>
        public static string GlobalButtonCreateLobby {
            get {
                return ResourceManager.GetString("GlobalButtonCreateLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string GlobalButtonEdit {
            get {
                return ResourceManager.GetString("GlobalButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a una sala.
        /// </summary>
        public static string GlobalButtonJoinLobby {
            get {
                return ResourceManager.GetString("GlobalButtonJoinLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazar.
        /// </summary>
        public static string GlobalButtonReject {
            get {
                return ResourceManager.GetString("GlobalButtonReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string GlobalButtonSaveChanges {
            get {
                return ResourceManager.GetString("GlobalButtonSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarme.
        /// </summary>
        public static string GlobalButtonSignUp {
            get {
                return ResourceManager.GetString("GlobalButtonSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar.
        /// </summary>
        public static string GlobalButtonStart {
            get {
                return ResourceManager.GetString("GlobalButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de Verificación.
        /// </summary>
        public static string GlobalButtonVerificationCode {
            get {
                return ResourceManager.GetString("GlobalButtonVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificar Código.
        /// </summary>
        public static string GlobalButtonVerifyCode {
            get {
                return ResourceManager.GetString("GlobalButtonVerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat.
        /// </summary>
        public static string GlobalLabelChat {
            get {
                return ResourceManager.GetString("GlobalLabelChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Contraseña.
        /// </summary>
        public static string GlobalLabelConfirmPassword {
            get {
                return ResourceManager.GetString("GlobalLabelConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tus datos para continuar.
        /// </summary>
        public static string GlobalLabelDetailsToContinue {
            get {
                return ResourceManager.GetString("GlobalLabelDetailsToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico.
        /// </summary>
        public static string GlobalLabelEmail {
            get {
                return ResourceManager.GetString("GlobalLabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala.
        /// </summary>
        public static string GlobalLabelLobby {
            get {
                return ResourceManager.GetString("GlobalLabelLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Materno.
        /// </summary>
        public static string GlobalLabelMaternalLastName {
            get {
                return ResourceManager.GetString("GlobalLabelMaternalLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre(s).
        /// </summary>
        public static string GlobalLabelName {
            get {
                return ResourceManager.GetString("GlobalLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Contraseña.
        /// </summary>
        public static string GlobalLabelNewPassword {
            get {
                return ResourceManager.GetString("GlobalLabelNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apodo.
        /// </summary>
        public static string GlobalLabelNickname {
            get {
                return ResourceManager.GetString("GlobalLabelNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string GlobalLabelPassword {
            get {
                return ResourceManager.GetString("GlobalLabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Paterno.
        /// </summary>
        public static string GlobalLabelPaternalLastName {
            get {
                return ResourceManager.GetString("GlobalLabelPaternalLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugadores.
        /// </summary>
        public static string GlobalLabelPlayers {
            get {
                return ResourceManager.GetString("GlobalLabelPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hemos enviado un código a.
        /// </summary>
        public static string GlobalLabelVerificationCode {
            get {
                return ResourceManager.GetString("GlobalLabelVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar correo electrónico.
        /// </summary>
        public static string GlobalTagChangeEmail {
            get {
                return ResourceManager.GetString("GlobalTagChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string GlobalTagNo {
            get {
                return ResourceManager.GetString("GlobalTagNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Contraseña.
        /// </summary>
        public static string GlobalTagPassword {
            get {
                return ResourceManager.GetString("GlobalTagPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        public static string GlobalTagYes {
            get {
                return ResourceManager.GetString("GlobalTagYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string GobalButtonSend {
            get {
                return ResourceManager.GetString("GobalButtonSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tu apodo.
        /// </summary>
        public static string GuestSignUpLabelNickname {
            get {
                return ResourceManager.GetString("GuestSignUpLabelNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar como invitado.
        /// </summary>
        public static string GuestSignUpLabelTitle {
            get {
                return ResourceManager.GetString("GuestSignUpLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar a un amigo.
        /// </summary>
        public static string InviteFriendButton {
            get {
                return ResourceManager.GetString("InviteFriendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir.
        /// </summary>
        public static string InviteFriendsButtonAdd {
            get {
                return ResourceManager.GetString("InviteFriendsButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar Solicitud.
        /// </summary>
        public static string InviteFriendsButtonCancelRequest {
            get {
                return ResourceManager.GetString("InviteFriendsButtonCancelRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copiar.
        /// </summary>
        public static string InviteFriendsButtonCopy {
            get {
                return ResourceManager.GetString("InviteFriendsButtonCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de Invitación.
        /// </summary>
        public static string InviteFriendsButtonInviteCode {
            get {
                return ResourceManager.GetString("InviteFriendsButtonInviteCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string InviteFriendsButtonSearch {
            get {
                return ResourceManager.GetString("InviteFriendsButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver solicitudes de amistad.
        /// </summary>
        public static string InviteFriendsButtonViewRequest {
            get {
                return ResourceManager.GetString("InviteFriendsButtonViewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copia tu código de invitación.
        /// </summary>
        public static string InviteFriendsLabelCopyInviteCode {
            get {
                return ResourceManager.GetString("InviteFriendsLabelCopyInviteCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Amigos.
        /// </summary>
        public static string InviteFriendsLabelMyFriends {
            get {
                return ResourceManager.GetString("InviteFriendsLabelMyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Jugador.
        /// </summary>
        public static string InviteFriendsLabelSearchPlayer {
            get {
                return ResourceManager.GetString("InviteFriendsLabelSearchPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar por correo electrónico.
        /// </summary>
        public static string InviteFriendsLabelSendEmail {
            get {
                return ResourceManager.GetString("InviteFriendsLabelSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invita a tu amigo.
        /// </summary>
        public static string InviteFriendsLabelTitle {
            get {
                return ResourceManager.GetString("InviteFriendsLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirme a la sala.
        /// </summary>
        public static string JoinLobbyButtonJoin {
            get {
                return ResourceManager.GetString("JoinLobbyButtonJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el código de la sala.
        /// </summary>
        public static string JoinLobbyLabelDetails {
            get {
                return ResourceManager.GetString("JoinLobbyLabelDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de la sala.
        /// </summary>
        public static string JoinLobbyLabelLobbyCode {
            get {
                return ResourceManager.GetString("JoinLobbyLabelLobbyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expulsión.
        /// </summary>
        public static string KickPlayerLabelKickOut {
            get {
                return ResourceManager.GetString("KickPlayerLabelKickOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estas seguro que deseas expulsar a.
        /// </summary>
        public static string KickPlayerLabelMessage {
            get {
                return ResourceManager.GetString("KickPlayerLabelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe un mensaje.
        /// </summary>
        public static string KickPlayerTextFieldChat {
            get {
                return ResourceManager.GetString("KickPlayerTextFieldChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabla de clasificación.
        /// </summary>
        public static string LeaderboardLabelTitle {
            get {
                return ResourceManager.GetString("LeaderboardLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Posición.
        /// </summary>
        public static string LeaderboardRankLabel {
            get {
                return ResourceManager.GetString("LeaderboardRankLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntuación.
        /// </summary>
        public static string LeaderboardScoreLabel {
            get {
                return ResourceManager.GetString("LeaderboardScoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a inicio.
        /// </summary>
        public static string loadMain {
            get {
                return ResourceManager.GetString("loadMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar.
        /// </summary>
        public static string LobbyButtonInvite {
            get {
                return ResourceManager.GetString("LobbyButtonInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expulsar.
        /// </summary>
        public static string LobbyButtonKick {
            get {
                return ResourceManager.GetString("LobbyButtonKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir del Lobby.
        /// </summary>
        public static string LobbyButtonLeaveLobby {
            get {
                return ResourceManager.GetString("LobbyButtonLeaveLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empezar Partida.
        /// </summary>
        public static string LobbyButtonStartGame {
            get {
                return ResourceManager.GetString("LobbyButtonStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Jugadores.
        /// </summary>
        public static string LobbyButtonViewPlayers {
            get {
                return ResourceManager.GetString("LobbyButtonViewPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modo de juego.
        /// </summary>
        public static string LobbyLabelGameMode {
            get {
                return ResourceManager.GetString("LobbyLabelGameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar Amigos.
        /// </summary>
        public static string LobbyLabelInviteFriends {
            get {
                return ResourceManager.GetString("LobbyLabelInviteFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Olvidé mi contraseña.
        /// </summary>
        public static string LoginButtonForgotMyPassword {
            get {
                return ResourceManager.GetString("LoginButtonForgotMyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soy nuevo, quiero registrarme.
        /// </summary>
        public static string LoginButtonSignUp {
            get {
                return ResourceManager.GetString("LoginButtonSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tus datos para iniciar.
        /// </summary>
        public static string LoginLabelEnterDetail {
            get {
                return ResourceManager.GetString("LoginLabelEnterDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de Sesión.
        /// </summary>
        public static string LoginLabelTitle {
            get {
                return ResourceManager.GetString("LoginLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigos.
        /// </summary>
        public static string MainMenuButtonFriends {
            get {
                return ResourceManager.GetString("MainMenuButtonFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        public static string MainMenuButtonProfile {
            get {
                return ResourceManager.GetString("MainMenuButtonProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        public static string MainMenuButtonSettings {
            get {
                return ResourceManager.GetString("MainMenuButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        public static string RecoverPasswordButtonConfirm {
            get {
                return ResourceManager.GetString("RecoverPasswordButtonConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a inicio de sesión.
        /// </summary>
        public static string RecoverPasswordButtonGoToLogin {
            get {
                return ResourceManager.GetString("RecoverPasswordButtonGoToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperar contraseña.
        /// </summary>
        public static string RecoverPasswordButtonRecoverPassword {
            get {
                return ResourceManager.GetString("RecoverPasswordButtonRecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al presionar “Recuperar contraseña”, se enviará un código de verificación a la dirección de correo electrónico proporcionada..
        /// </summary>
        public static string RecoverPasswordLabelDescription {
            get {
                return ResourceManager.GetString("RecoverPasswordLabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tu nueva contraseña para continuar.
        /// </summary>
        public static string RecoverPasswordLabelNewPassword {
            get {
                return ResourceManager.GetString("RecoverPasswordLabelNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu contraseña se ha actualizado correctamente, ya puedes iniciar sesión.
        /// </summary>
        public static string RecoverPasswordLabelPasswordUpdated {
            get {
                return ResourceManager.GetString("RecoverPasswordLabelPasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperar Contraseña.
        /// </summary>
        public static string RecoverPasswordLabelTitle {
            get {
                return ResourceManager.GetString("RecoverPasswordLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tus datos para registrarte.
        /// </summary>
        public static string UserSignUpLabelDetails {
            get {
                return ResourceManager.GetString("UserSignUpLabelDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu registro ha sido completado exitosamente. Bienvenido.
        /// </summary>
        public static string UserSignUpLabelRegistrationComplete {
            get {
                return ResourceManager.GetString("UserSignUpLabelRegistrationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de Usuario.
        /// </summary>
        public static string UserSignUpLabelTitle {
            get {
                return ResourceManager.GetString("UserSignUpLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falso Ganador.
        /// </summary>
        public static string WinnerButtonFalseWinner {
            get {
                return ResourceManager.GetString("WinnerButtonFalseWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ganador.
        /// </summary>
        public static string WinnerLabelTitle {
            get {
                return ResourceManager.GetString("WinnerLabelTitle", resourceCulture);
            }
        }
    }
}
