//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lottery.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aang.
        /// </summary>
        public static string CardTextBlockAang {
            get {
                return ResourceManager.GetString("CardTextBlockAang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arnold.
        /// </summary>
        public static string CardTextBlockArnold {
            get {
                return ResourceManager.GetString("CardTextBlockArnold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ash Ketchum.
        /// </summary>
        public static string CardTextBlockAshKetchum {
            get {
                return ResourceManager.GetString("CardTextBlockAshKetchum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bart Simpson.
        /// </summary>
        public static string CardTextBlockBartSimpson {
            get {
                return ResourceManager.GetString("CardTextBlockBartSimpson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ben 10.
        /// </summary>
        public static string CardTextBlockBenTen {
            get {
                return ResourceManager.GetString("CardTextBlockBenTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Billy.
        /// </summary>
        public static string CardTextBlockBilly {
            get {
                return ResourceManager.GetString("CardTextBlockBilly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bombón.
        /// </summary>
        public static string CardTextBlockBlossom {
            get {
                return ResourceManager.GetString("CardTextBlockBlossom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerebro.
        /// </summary>
        public static string CardTextBlockBrain {
            get {
                return ResourceManager.GetString("CardTextBlockBrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Brock.
        /// </summary>
        public static string CardTextBlockBrock {
            get {
                return ResourceManager.GetString("CardTextBlockBrock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Burbuja.
        /// </summary>
        public static string CardTextBlockBubbles {
            get {
                return ResourceManager.GetString("CardTextBlockBubbles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bellota.
        /// </summary>
        public static string CardTextBlockButtercup {
            get {
                return ResourceManager.GetString("CardTextBlockButtercup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GatoPerro.
        /// </summary>
        public static string CardTextBlockCatDog {
            get {
                return ResourceManager.GetString("CardTextBlockCatDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carlitos Baldosa.
        /// </summary>
        public static string CardTextBlockChuckieFinster {
            get {
                return ResourceManager.GetString("CardTextBlockChuckieFinster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cosmo.
        /// </summary>
        public static string CardTextBlockCosmo {
            get {
                return ResourceManager.GetString("CardTextBlockCosmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coraje.
        /// </summary>
        public static string CardTextBlockCourage {
            get {
                return ResourceManager.GetString("CardTextBlockCourage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dexter.
        /// </summary>
        public static string CardTextBlockDexter {
            get {
                return ResourceManager.GetString("CardTextBlockDexter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dipper Pines.
        /// </summary>
        public static string CardTextBlockDipperPines {
            get {
                return ResourceManager.GetString("CardTextBlockDipperPines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edd.
        /// </summary>
        public static string CardTextBlockEdd {
            get {
                return ResourceManager.GetString("CardTextBlockEdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eddy.
        /// </summary>
        public static string CardTextBlockEddy {
            get {
                return ResourceManager.GetString("CardTextBlockEddy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ferb.
        /// </summary>
        public static string CardTextBlockFerb {
            get {
                return ResourceManager.GetString("CardTextBlockFerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finn El Humano.
        /// </summary>
        public static string CardTextBlockFinnTheHuman {
            get {
                return ResourceManager.GetString("CardTextBlockFinnTheHuman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Goku.
        /// </summary>
        public static string CardTextBlockGoku {
            get {
                return ResourceManager.GetString("CardTextBlockGoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Homero Simpson.
        /// </summary>
        public static string CardTextBlockHomerSimpson {
            get {
                return ResourceManager.GetString("CardTextBlockHomerSimpson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jake El Perro.
        /// </summary>
        public static string CardTextBlockJakeTheDog {
            get {
                return ResourceManager.GetString("CardTextBlockJakeTheDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jerry.
        /// </summary>
        public static string CardTextBlockJerry {
            get {
                return ResourceManager.GetString("CardTextBlockJerry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kim Posible.
        /// </summary>
        public static string CardTextBlockKimPossible {
            get {
                return ResourceManager.GetString("CardTextBlockKimPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lisa Simpson.
        /// </summary>
        public static string CardTextBlockLisaSimpson {
            get {
                return ResourceManager.GetString("CardTextBlockLisaSimpson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mabel Pines.
        /// </summary>
        public static string CardTextBlockMabelPines {
            get {
                return ResourceManager.GetString("CardTextBlockMabelPines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mickey Mouse.
        /// </summary>
        public static string CardTextBlockMickeyMouse {
            get {
                return ResourceManager.GetString("CardTextBlockMickeyMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Misty.
        /// </summary>
        public static string CardTextBlockMisty {
            get {
                return ResourceManager.GetString("CardTextBlockMisty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mordecai.
        /// </summary>
        public static string CardTextBlockMordecai {
            get {
                return ResourceManager.GetString("CardTextBlockMordecai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Morty Smith.
        /// </summary>
        public static string CardTextBlockMortySmith {
            get {
                return ResourceManager.GetString("CardTextBlockMortySmith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Don Cangrejo.
        /// </summary>
        public static string CardTextBlockMrKrabs {
            get {
                return ResourceManager.GetString("CardTextBlockMrKrabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Naruto.
        /// </summary>
        public static string CardTextBlockNaruto {
            get {
                return ResourceManager.GetString("CardTextBlockNaruto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número 1.
        /// </summary>
        public static string CardTextBlockNumberOne {
            get {
                return ResourceManager.GetString("CardTextBlockNumberOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patricio Estrella.
        /// </summary>
        public static string CardTextBlockPatrickStar {
            get {
                return ResourceManager.GetString("CardTextBlockPatrickStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perry El Ornitorrinco.
        /// </summary>
        public static string CardTextBlockPerryThePlatypus {
            get {
                return ResourceManager.GetString("CardTextBlockPerryThePlatypus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phineas.
        /// </summary>
        public static string CardTextBlockPhineas {
            get {
                return ResourceManager.GetString("CardTextBlockPhineas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Picoro.
        /// </summary>
        public static string CardTextBlockPicoro {
            get {
                return ResourceManager.GetString("CardTextBlockPicoro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pikachu.
        /// </summary>
        public static string CardTextBlockPikachu {
            get {
                return ResourceManager.GetString("CardTextBlockPikachu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pinky.
        /// </summary>
        public static string CardTextBlockPinky {
            get {
                return ResourceManager.GetString("CardTextBlockPinky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esperando Carta . . ..
        /// </summary>
        public static string CardTextBlockReverse {
            get {
                return ResourceManager.GetString("CardTextBlockReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rick Sánchez.
        /// </summary>
        public static string CardTextBlockRickSanchez {
            get {
                return ResourceManager.GetString("CardTextBlockRickSanchez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rigby.
        /// </summary>
        public static string CardTextBlockRigby {
            get {
                return ResourceManager.GetString("CardTextBlockRigby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sailor Moon.
        /// </summary>
        public static string CardTextBlockSailorMoon {
            get {
                return ResourceManager.GetString("CardTextBlockSailorMoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scooby-Doo.
        /// </summary>
        public static string CardTextBlockScoobyDoo {
            get {
                return ResourceManager.GetString("CardTextBlockScoobyDoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shaggy.
        /// </summary>
        public static string CardTextBlockShaggy {
            get {
                return ResourceManager.GetString("CardTextBlockShaggy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shego.
        /// </summary>
        public static string CardTextBlockShego {
            get {
                return ResourceManager.GetString("CardTextBlockShego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Snoopy.
        /// </summary>
        public static string CardTextBlockSnoopy {
            get {
                return ResourceManager.GetString("CardTextBlockSnoopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bob Esponja.
        /// </summary>
        public static string CardTextBlockSpongeBob {
            get {
                return ResourceManager.GetString("CardTextBlockSpongeBob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stich.
        /// </summary>
        public static string CardTextBlockStich {
            get {
                return ResourceManager.GetString("CardTextBlockStich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tom.
        /// </summary>
        public static string CardTextBlockTom {
            get {
                return ResourceManager.GetString("CardTextBlockTom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tommy.
        /// </summary>
        public static string CardTextBlockTommy {
            get {
                return ResourceManager.GetString("CardTextBlockTommy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wanda.
        /// </summary>
        public static string CardTextBlockWanda {
            get {
                return ResourceManager.GetString("CardTextBlockWanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Pájaro Loco.
        /// </summary>
        public static string CardTextBlockWoodyWoodpecker {
            get {
                return ResourceManager.GetString("CardTextBlockWoodyWoodpecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear nueva contraseña.
        /// </summary>
        public static string ChangePasswordButtonCreateNewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordButtonCreateNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña actual.
        /// </summary>
        public static string ChangePasswordLabelCurrentPassword {
            get {
                return ResourceManager.GetString("ChangePasswordLabelCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu contraseña se ha modificado correctamente.
        /// </summary>
        public static string ChangePasswordLabelSuccessfullyChanged {
            get {
                return ResourceManager.GetString("ChangePasswordLabelSuccessfullyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código solo puede contener números..
        /// </summary>
        public static string CodeFormatMessage {
            get {
                return ResourceManager.GetString("CodeFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código de verificación debe contener exactamente 6 dígitos..
        /// </summary>
        public static string CodeLengthMessage {
            get {
                return ResourceManager.GetString("CodeLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código no puede estar vacío..
        /// </summary>
        public static string CodeRequiredMessage {
            get {
                return ResourceManager.GetString("CodeRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1 Segundo.
        /// </summary>
        public static string CreateLobbyLabelCardDisplayOneSecond {
            get {
                return ResourceManager.GetString("CreateLobbyLabelCardDisplayOneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3 Segundos.
        /// </summary>
        public static string CreateLobbyLabelCardDisplayThreeSeconds {
            get {
                return ResourceManager.GetString("CreateLobbyLabelCardDisplayThreeSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo de aparición de las cartas.
        /// </summary>
        public static string CreateLobbyLabelCardDisplayTime {
            get {
                return ResourceManager.GetString("CreateLobbyLabelCardDisplayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2 Segundos.
        /// </summary>
        public static string CreateLobbyLabelCardDisplayTwoSeconds {
            get {
                return ResourceManager.GetString("CreateLobbyLabelCardDisplayTwoSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen de cartas.
        /// </summary>
        public static string CreateLobbyLabelCardImage {
            get {
                return ResourceManager.GetString("CreateLobbyLabelCardImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Centro.
        /// </summary>
        public static string CreateLobbyLabelGameModeCenter {
            get {
                return ResourceManager.GetString("CreateLobbyLabelGameModeCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esquinas.
        /// </summary>
        public static string CreateLobbyLabelGameModeCorners {
            get {
                return ResourceManager.GetString("CreateLobbyLabelGameModeCorners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diagonales.
        /// </summary>
        public static string CreateLobbyLabelGameModeDiagonals {
            get {
                return ResourceManager.GetString("CreateLobbyLabelGameModeDiagonals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marco.
        /// </summary>
        public static string CreateLobbyLabelGameModeFrame {
            get {
                return ResourceManager.GetString("CreateLobbyLabelGameModeFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mega Lotería.
        /// </summary>
        public static string CreateLobbyLabelGameModeMegaLottery {
            get {
                return ResourceManager.GetString("CreateLobbyLabelGameModeMegaLottery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Normal.
        /// </summary>
        public static string CreateLobbyLabelGameModeStandard {
            get {
                return ResourceManager.GetString("CreateLobbyLabelGameModeStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lotería Injusta.
        /// </summary>
        public static string CreateLobbyLabelGameModeUnfairLottery {
            get {
                return ResourceManager.GetString("CreateLobbyLabelGameModeUnfairLottery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fichas.
        /// </summary>
        public static string CreateLobbyLabelMarkers {
            get {
                return ResourceManager.GetString("CreateLobbyLabelMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frijoles.
        /// </summary>
        public static string CreateLobbyLabelMarkersBeans {
            get {
                return ResourceManager.GetString("CreateLobbyLabelMarkersBeans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Corcholatas.
        /// </summary>
        public static string CreateLobbyLabelMarkersBottleCaps {
            get {
                return ResourceManager.GetString("CreateLobbyLabelMarkersBottleCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monedas.
        /// </summary>
        public static string CreateLobbyLabelMarkersCoins {
            get {
                return ResourceManager.GetString("CreateLobbyLabelMarkersCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maíz.
        /// </summary>
        public static string CreateLobbyLabelMarkersCorn {
            get {
                return ResourceManager.GetString("CreateLobbyLabelMarkersCorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bolitas de Papel.
        /// </summary>
        public static string CreateLobbyLabelMarkersPaperBalls {
            get {
                return ResourceManager.GetString("CreateLobbyLabelMarkersPaperBalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sonido.
        /// </summary>
        public static string CreateLobbyLabelSound {
            get {
                return ResourceManager.GetString("CreateLobbyLabelSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Avatar.
        /// </summary>
        public static string CustomizeProfileButtonChangeAvatar {
            get {
                return ResourceManager.GetString("CustomizeProfileButtonChangeAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Correo.
        /// </summary>
        public static string CustomizeProfileButtonChangeEmail {
            get {
                return ResourceManager.GetString("CustomizeProfileButtonChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Apodo.
        /// </summary>
        public static string CustomizeProfileButtonChangeNickname {
            get {
                return ResourceManager.GetString("CustomizeProfileButtonChangeNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Contraseña.
        /// </summary>
        public static string CustomizeProfileButtonChangePassword {
            get {
                return ResourceManager.GetString("CustomizeProfileButtonChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Foto de Perfil.
        /// </summary>
        public static string CustomizeProfileLabelAvatar {
            get {
                return ResourceManager.GetString("CustomizeProfileLabelAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color de Fondo.
        /// </summary>
        public static string CustomizeProfileLabelBackground {
            get {
                return ResourceManager.GetString("CustomizeProfileLabelBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al presionar “Continuar”, se enviará un código de verificación a la dirección de correo electrónico proporcionada..
        /// </summary>
        public static string CustomizeProfileLabelDescription {
            get {
                return ResourceManager.GetString("CustomizeProfileLabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edita y actualiza la información de tu perfil..
        /// </summary>
        public static string CustomizeProfileLabelEditDetails {
            get {
                return ResourceManager.GetString("CustomizeProfileLabelEditDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu correo electrónico se ha modificado correctamente.
        /// </summary>
        public static string CustomizeProfileLabelEmailUpdated {
            get {
                return ResourceManager.GetString("CustomizeProfileLabelEmailUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva dirección de correo electrónico.
        /// </summary>
        public static string CustomizeProfileLabelNewEmailAddress {
            get {
                return ResourceManager.GetString("CustomizeProfileLabelNewEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos del Perfil.
        /// </summary>
        public static string CustomizeProfileLabelProfileDetails {
            get {
                return ResourceManager.GetString("CustomizeProfileLabelProfileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona tu avatar.
        /// </summary>
        public static string CustomizeProfileLabelSelectAvatar {
            get {
                return ResourceManager.GetString("CustomizeProfileLabelSelectAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Redes Sociales.
        /// </summary>
        public static string CustomizeProfileLabelSocialMedia {
            get {
                return ResourceManager.GetString("CustomizeProfileLabelSocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalizar Perfil.
        /// </summary>
        public static string CustomizeProfileLabelTitle {
            get {
                return ResourceManager.GetString("CustomizeProfileLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar amigo.
        /// </summary>
        public static string DeleteFriendButton {
            get {
                return ResourceManager.GetString("DeleteFriendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo contiene caracteres no permitidos o dominio inválido..
        /// </summary>
        public static string EmailInvalidDomainOrCharsMessage {
            get {
                return ResourceManager.GetString("EmailInvalidDomainOrCharsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de correo electrónico no válido..
        /// </summary>
        public static string EmailInvalidFormatMessage {
            get {
                return ResourceManager.GetString("EmailInvalidFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo es obligatorio..
        /// </summary>
        public static string EmailRequiredMessage {
            get {
                return ResourceManager.GetString("EmailRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre solo puede contener letras y espacios..
        /// </summary>
        public static string FirstNameInvalidCharactersMessage {
            get {
                return ResourceManager.GetString("FirstNameInvalidCharactersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre debe contener máximo 30 caracteres..
        /// </summary>
        public static string FirstNameMaxLengthMessage {
            get {
                return ResourceManager.GetString("FirstNameMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre es obligatorio..
        /// </summary>
        public static string FirstNameRequiredMessage {
            get {
                return ResourceManager.GetString("FirstNameRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de conexión al cargar:.
        /// </summary>
        public static string FriendRequestsConnectionError {
            get {
                return ResourceManager.GetString("FriendRequestsConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error cargando solicitudes: {0}.
        /// </summary>
        public static string FriendRequestsErrorLoadingRequests {
            get {
                return ResourceManager.GetString("FriendRequestsErrorLoadingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor tuvo un problema interno. Intenta más tarde..
        /// </summary>
        public static string FriendRequestsExceptionFR500 {
            get {
                return ResourceManager.GetString("FriendRequestsExceptionFR500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya eres amigo de este usuario o la solicitud ya fue procesada..
        /// </summary>
        public static string FriendRequestsExceptionFriendDuplicate {
            get {
                return ResourceManager.GetString("FriendRequestsExceptionFriendDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La operación de amistad no es válida..
        /// </summary>
        public static string FriendRequestsExceptionFriendInvalid {
            get {
                return ResourceManager.GetString("FriendRequestsExceptionFriendInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta solicitud ya fue aceptada o cancelada por el otro usuario..
        /// </summary>
        public static string FriendRequestsExceptionFriendNotFound {
            get {
                return ResourceManager.GetString("FriendRequestsExceptionFriendNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu sesión ha expirado. Por favor cierra sesión y vuelve a entrar..
        /// </summary>
        public static string FriendRequestsExceptionUserOffline {
            get {
                return ResourceManager.GetString("FriendRequestsExceptionUserOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ahora eres amigo de {0}.
        /// </summary>
        public static string FriendRequestsNowFriendWith {
            get {
                return ResourceManager.GetString("FriendRequestsNowFriendWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo aceptar la solicitud de amistad.
        /// </summary>
        public static string FriendRequestsRequestCouldNotBeAccepted {
            get {
                return ResourceManager.GetString("FriendRequestsRequestCouldNotBeAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo rechazar la solicitud de amistad.
        /// </summary>
        public static string FriendRequestsRequestCouldNotBeReject {
            get {
                return ResourceManager.GetString("FriendRequestsRequestCouldNotBeReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de Sesión.
        /// </summary>
        public static string FriendRequestsSessionError {
            get {
                return ResourceManager.GetString("FriendRequestsSessionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de amigos.
        /// </summary>
        public static string FriendsListLabelTitle {
            get {
                return ResourceManager.GetString("FriendsListLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string GlobalButtonAccept {
            get {
                return ResourceManager.GetString("GlobalButtonAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string GlobalButtonBack {
            get {
                return ResourceManager.GetString("GlobalButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string GlobalButtonCancel {
            get {
                return ResourceManager.GetString("GlobalButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar.
        /// </summary>
        public static string GlobalButtonContinue {
            get {
                return ResourceManager.GetString("GlobalButtonContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Sala.
        /// </summary>
        public static string GlobalButtonCreateLobby {
            get {
                return ResourceManager.GetString("GlobalButtonCreateLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string GlobalButtonEdit {
            get {
                return ResourceManager.GetString("GlobalButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a una sala.
        /// </summary>
        public static string GlobalButtonJoinLobby {
            get {
                return ResourceManager.GetString("GlobalButtonJoinLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazar.
        /// </summary>
        public static string GlobalButtonReject {
            get {
                return ResourceManager.GetString("GlobalButtonReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string GlobalButtonSaveChanges {
            get {
                return ResourceManager.GetString("GlobalButtonSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarme.
        /// </summary>
        public static string GlobalButtonSignUp {
            get {
                return ResourceManager.GetString("GlobalButtonSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar.
        /// </summary>
        public static string GlobalButtonStart {
            get {
                return ResourceManager.GetString("GlobalButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de Verificación.
        /// </summary>
        public static string GlobalButtonVerificationCode {
            get {
                return ResourceManager.GetString("GlobalButtonVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificar Código.
        /// </summary>
        public static string GlobalButtonVerifyCode {
            get {
                return ResourceManager.GetString("GlobalButtonVerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error interno del servidor.
        /// </summary>
        public static string GlobalExceptionInternalServerError {
            get {
                return ResourceManager.GetString("GlobalExceptionInternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error del servidor ({0}): {1}.
        /// </summary>
        public static string GlobalExceptionServerError {
            get {
                return ResourceManager.GetString("GlobalExceptionServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat.
        /// </summary>
        public static string GlobalLabelChat {
            get {
                return ResourceManager.GetString("GlobalLabelChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Contraseña.
        /// </summary>
        public static string GlobalLabelConfirmPassword {
            get {
                return ResourceManager.GetString("GlobalLabelConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tus datos para continuar.
        /// </summary>
        public static string GlobalLabelDetailsToContinue {
            get {
                return ResourceManager.GetString("GlobalLabelDetailsToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico.
        /// </summary>
        public static string GlobalLabelEmail {
            get {
                return ResourceManager.GetString("GlobalLabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala.
        /// </summary>
        public static string GlobalLabelLobby {
            get {
                return ResourceManager.GetString("GlobalLabelLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Materno.
        /// </summary>
        public static string GlobalLabelMaternalLastName {
            get {
                return ResourceManager.GetString("GlobalLabelMaternalLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre(s).
        /// </summary>
        public static string GlobalLabelName {
            get {
                return ResourceManager.GetString("GlobalLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Contraseña.
        /// </summary>
        public static string GlobalLabelNewPassword {
            get {
                return ResourceManager.GetString("GlobalLabelNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apodo.
        /// </summary>
        public static string GlobalLabelNickname {
            get {
                return ResourceManager.GetString("GlobalLabelNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string GlobalLabelPassword {
            get {
                return ResourceManager.GetString("GlobalLabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Paterno.
        /// </summary>
        public static string GlobalLabelPaternalLastName {
            get {
                return ResourceManager.GetString("GlobalLabelPaternalLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugadores.
        /// </summary>
        public static string GlobalLabelPlayers {
            get {
                return ResourceManager.GetString("GlobalLabelPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hemos enviado un código a.
        /// </summary>
        public static string GlobalLabelVerificationCode {
            get {
                return ResourceManager.GetString("GlobalLabelVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        public static string GlobalMessageBoxTitleConfirm {
            get {
                return ResourceManager.GetString("GlobalMessageBoxTitleConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string GlobalMessageBoxTitleError {
            get {
                return ResourceManager.GetString("GlobalMessageBoxTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviado.
        /// </summary>
        public static string GlobalMessageBoxTitleSent {
            get {
                return ResourceManager.GetString("GlobalMessageBoxTitleSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Éxito.
        /// </summary>
        public static string GlobalMessageBoxTitleSuccess {
            get {
                return ResourceManager.GetString("GlobalMessageBoxTitleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error inesperado: {0}.
        /// </summary>
        public static string GlobalMessageBoxUnexpectedError {
            get {
                return ResourceManager.GetString("GlobalMessageBoxUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar correo electrónico.
        /// </summary>
        public static string GlobalTagChangeEmail {
            get {
                return ResourceManager.GetString("GlobalTagChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string GlobalTagNo {
            get {
                return ResourceManager.GetString("GlobalTagNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Contraseña.
        /// </summary>
        public static string GlobalTagPassword {
            get {
                return ResourceManager.GetString("GlobalTagPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        public static string GlobalTagYes {
            get {
                return ResourceManager.GetString("GlobalTagYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string GobalButtonSend {
            get {
                return ResourceManager.GetString("GobalButtonSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tu apodo.
        /// </summary>
        public static string GuestSignUpLabelNickname {
            get {
                return ResourceManager.GetString("GuestSignUpLabelNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar como invitado.
        /// </summary>
        public static string GuestSignUpLabelTitle {
            get {
                return ResourceManager.GetString("GuestSignUpLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} ahora es tu amigo.
        /// </summary>
        public static string IniviteFriendsSucces {
            get {
                return ResourceManager.GetString("IniviteFriendsSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar a un amigo.
        /// </summary>
        public static string InviteFriendButton {
            get {
                return ResourceManager.GetString("InviteFriendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cancelar.
        /// </summary>
        public static string InviteFriendErrorCanceling {
            get {
                return ResourceManager.GetString("InviteFriendErrorCanceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que quieres eliminar a {0}?.
        /// </summary>
        public static string InviteFriendsAreYouSure {
            get {
                return ResourceManager.GetString("InviteFriendsAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir.
        /// </summary>
        public static string InviteFriendsButtonAdd {
            get {
                return ResourceManager.GetString("InviteFriendsButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar Solicitud.
        /// </summary>
        public static string InviteFriendsButtonCancelRequest {
            get {
                return ResourceManager.GetString("InviteFriendsButtonCancelRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copiar.
        /// </summary>
        public static string InviteFriendsButtonCopy {
            get {
                return ResourceManager.GetString("InviteFriendsButtonCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de Invitación.
        /// </summary>
        public static string InviteFriendsButtonInviteCode {
            get {
                return ResourceManager.GetString("InviteFriendsButtonInviteCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string InviteFriendsButtonSearch {
            get {
                return ResourceManager.GetString("InviteFriendsButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver solicitudes de amistad.
        /// </summary>
        public static string InviteFriendsButtonViewRequest {
            get {
                return ResourceManager.GetString("InviteFriendsButtonViewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de amistad cancelada.
        /// </summary>
        public static string InviteFriendsCancelRequest {
            get {
                return ResourceManager.GetString("InviteFriendsCancelRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de conexión: {0}.
        /// </summary>
        public static string InviteFriendsConnectionError {
            get {
                return ResourceManager.GetString("InviteFriendsConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error {0}.
        /// </summary>
        public static string InviteFriendsError {
            get {
                return ResourceManager.GetString("InviteFriendsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de invitación.
        /// </summary>
        public static string InviteFriendsErrorInvitation {
            get {
                return ResourceManager.GetString("InviteFriendsErrorInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar amigos.
        /// </summary>
        public static string InviteFriendsErrorLoadingFriends {
            get {
                return ResourceManager.GetString("InviteFriendsErrorLoadingFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al aceptar.
        /// </summary>
        public static string InviteFriendsErrorWhenAccepting {
            get {
                return ResourceManager.GetString("InviteFriendsErrorWhenAccepting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar.
        /// </summary>
        public static string InviteFriendsErrorWhenDeleting {
            get {
                return ResourceManager.GetString("InviteFriendsErrorWhenDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al rechazar.
        /// </summary>
        public static string InviteFriendsErrorWhenRejecting {
            get {
                return ResourceManager.GetString("InviteFriendsErrorWhenRejecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe una solicitud pendiente o una amistad con .
        /// </summary>
        public static string InviteFriendsExceptionFriendDuplicate {
            get {
                return ResourceManager.GetString("InviteFriendsExceptionFriendDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes invitar amigos siendo invitado..
        /// </summary>
        public static string InviteFriendsExceptionFriendGuestRestricted {
            get {
                return ResourceManager.GetString("InviteFriendsExceptionFriendGuestRestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación de amistad no válida..
        /// </summary>
        public static string InviteFriendsExceptionFriendInvalid {
            get {
                return ResourceManager.GetString("InviteFriendsExceptionFriendInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La solicitud de amistad no existe, ya fue aceptada o rechazada por la otra parte..
        /// </summary>
        public static string InviteFriendsExceptionFriendNotFound {
            get {
                return ResourceManager.GetString("InviteFriendsExceptionFriendNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ya se encuentra ocupado en un lobby..
        /// </summary>
        public static string InviteFriendsExceptionUserInLobby {
            get {
                return ResourceManager.GetString("InviteFriendsExceptionUserInLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró ningún usuario con ese apodo..
        /// </summary>
        public static string InviteFriendsExceptionUserNotFound {
            get {
                return ResourceManager.GetString("InviteFriendsExceptionUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no está conectado actualmente o tu sesión expiró..
        /// </summary>
        public static string InviteFriendsExceptionUserOffline {
            get {
                return ResourceManager.GetString("InviteFriendsExceptionUserOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de amistad rechazada.
        /// </summary>
        public static string InviteFriendsFriendRequestRejected {
            get {
                return ResourceManager.GetString("InviteFriendsFriendRequestRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copia tu código de invitación.
        /// </summary>
        public static string InviteFriendsLabelCopyInviteCode {
            get {
                return ResourceManager.GetString("InviteFriendsLabelCopyInviteCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Amigos.
        /// </summary>
        public static string InviteFriendsLabelMyFriends {
            get {
                return ResourceManager.GetString("InviteFriendsLabelMyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Jugador.
        /// </summary>
        public static string InviteFriendsLabelSearchPlayer {
            get {
                return ResourceManager.GetString("InviteFriendsLabelSearchPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar por correo electrónico.
        /// </summary>
        public static string InviteFriendsLabelSendEmail {
            get {
                return ResourceManager.GetString("InviteFriendsLabelSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invita a tu amigo.
        /// </summary>
        public static string InviteFriendsLabelTitle {
            get {
                return ResourceManager.GetString("InviteFriendsLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo enviar.
        /// </summary>
        public static string InviteFriendsNotSent {
            get {
                return ResourceManager.GetString("InviteFriendsNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud enviada a {0}.
        /// </summary>
        public static string InviteFriendsRequestsSent {
            get {
                return ResourceManager.GetString("InviteFriendsRequestsSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Búsqueda.
        /// </summary>
        public static string InviteFriendsSearch {
            get {
                return ResourceManager.GetString("InviteFriendsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en Búsqueda.
        /// </summary>
        public static string InviteFriendsSearchError {
            get {
                return ResourceManager.GetString("InviteFriendsSearchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitación enviada a {0}.
        /// </summary>
        public static string InviteFriendsSucces {
            get {
                return ResourceManager.GetString("InviteFriendsSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirme a la sala.
        /// </summary>
        public static string JoinLobbyButtonJoin {
            get {
                return ResourceManager.GetString("JoinLobbyButtonJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el código de la sala.
        /// </summary>
        public static string JoinLobbyLabelDetails {
            get {
                return ResourceManager.GetString("JoinLobbyLabelDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de la sala.
        /// </summary>
        public static string JoinLobbyLabelLobbyCode {
            get {
                return ResourceManager.GetString("JoinLobbyLabelLobbyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expulsión.
        /// </summary>
        public static string KickPlayerLabelKickOut {
            get {
                return ResourceManager.GetString("KickPlayerLabelKickOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estas seguro que deseas expulsar a.
        /// </summary>
        public static string KickPlayerLabelMessage {
            get {
                return ResourceManager.GetString("KickPlayerLabelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe un mensaje.
        /// </summary>
        public static string KickPlayerTextFieldChat {
            get {
                return ResourceManager.GetString("KickPlayerTextFieldChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabla de clasificación.
        /// </summary>
        public static string LeaderboardLabelTitle {
            get {
                return ResourceManager.GetString("LeaderboardLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Posición.
        /// </summary>
        public static string LeaderboardRankLabel {
            get {
                return ResourceManager.GetString("LeaderboardRankLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntuación.
        /// </summary>
        public static string LeaderboardScoreLabel {
            get {
                return ResourceManager.GetString("LeaderboardScoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a inicio.
        /// </summary>
        public static string loadMain {
            get {
                return ResourceManager.GetString("loadMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar.
        /// </summary>
        public static string LobbyButtonInvite {
            get {
                return ResourceManager.GetString("LobbyButtonInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expulsar.
        /// </summary>
        public static string LobbyButtonKick {
            get {
                return ResourceManager.GetString("LobbyButtonKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir del Lobby.
        /// </summary>
        public static string LobbyButtonLeaveLobby {
            get {
                return ResourceManager.GetString("LobbyButtonLeaveLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empezar Partida.
        /// </summary>
        public static string LobbyButtonStartGame {
            get {
                return ResourceManager.GetString("LobbyButtonStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Jugadores.
        /// </summary>
        public static string LobbyButtonViewPlayers {
            get {
                return ResourceManager.GetString("LobbyButtonViewPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modo de juego.
        /// </summary>
        public static string LobbyLabelGameMode {
            get {
                return ResourceManager.GetString("LobbyLabelGameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar Amigos.
        /// </summary>
        public static string LobbyLabelInviteFriends {
            get {
                return ResourceManager.GetString("LobbyLabelInviteFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Olvidé mi contraseña.
        /// </summary>
        public static string LoginButtonForgotMyPassword {
            get {
                return ResourceManager.GetString("LoginButtonForgotMyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soy nuevo, quiero registrarme.
        /// </summary>
        public static string LoginButtonSignUp {
            get {
                return ResourceManager.GetString("LoginButtonSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar como invitado.
        /// </summary>
        public static string LoginButtonStartGuest {
            get {
                return ResourceManager.GetString("LoginButtonStartGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tus datos para iniciar.
        /// </summary>
        public static string LoginLabelEnterDetail {
            get {
                return ResourceManager.GetString("LoginLabelEnterDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de Sesión.
        /// </summary>
        public static string LoginLabelTitle {
            get {
                return ResourceManager.GetString("LoginLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigos.
        /// </summary>
        public static string MainMenuButtonFriends {
            get {
                return ResourceManager.GetString("MainMenuButtonFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Sesión.
        /// </summary>
        public static string MainMenuButtonLogout {
            get {
                return ResourceManager.GetString("MainMenuButtonLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        public static string MainMenuButtonProfile {
            get {
                return ResourceManager.GetString("MainMenuButtonProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        public static string MainMenuButtonSettings {
            get {
                return ResourceManager.GetString("MainMenuButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apellido materno solo puede contener letras y espacios..
        /// </summary>
        public static string MaternalLastNameInvalidCharactersMessage {
            get {
                return ResourceManager.GetString("MaternalLastNameInvalidCharactersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apellido materno debe contener máximo 30 caracteres..
        /// </summary>
        public static string MaternalLastNameMaxLengthMessage {
            get {
                return ResourceManager.GetString("MaternalLastNameMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nickname solo puede contener letras, números y _ . -.
        /// </summary>
        public static string NicknameInvalidCharactersMessage {
            get {
                return ResourceManager.GetString("NicknameInvalidCharactersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nickname debe contener máximo 20 caracteres permitidos..
        /// </summary>
        public static string NicknameMaxLengthMessage {
            get {
                return ResourceManager.GetString("NicknameMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nickname debe tener mínimo 4 caracteres..
        /// </summary>
        public static string NicknameMinLengthMessage {
            get {
                return ResourceManager.GetString("NicknameMinLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nickname es obligatorio..
        /// </summary>
        public static string NicknameRequiredMessage {
            get {
                return ResourceManager.GetString("NicknameRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña contiene caracteres no permitidos..
        /// </summary>
        public static string PasswordInvalidCharactersMessage {
            get {
                return ResourceManager.GetString("PasswordInvalidCharactersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener mínimo 8 caracteres..
        /// </summary>
        public static string PasswordMinLengthMessage {
            get {
                return ResourceManager.GetString("PasswordMinLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña es obligatoria..
        /// </summary>
        public static string PasswordRequiredMessage {
            get {
                return ResourceManager.GetString("PasswordRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe contener al menos una letra minúscula..
        /// </summary>
        public static string PasswordRequireLowercaseMessage {
            get {
                return ResourceManager.GetString("PasswordRequireLowercaseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe contener al menos un número..
        /// </summary>
        public static string PasswordRequireNumberMessage {
            get {
                return ResourceManager.GetString("PasswordRequireNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe contener un carácter especial (! @ # $ % &amp; * _ - + =).
        /// </summary>
        public static string PasswordRequireSpecialCharMessage {
            get {
                return ResourceManager.GetString("PasswordRequireSpecialCharMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe contener al menos una letra mayúscula..
        /// </summary>
        public static string PasswordRequireUppercaseMessage {
            get {
                return ResourceManager.GetString("PasswordRequireUppercaseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apellido paterno solo puede contener letras y espacios..
        /// </summary>
        public static string PaternalLastNameInvalidCharactersMessage {
            get {
                return ResourceManager.GetString("PaternalLastNameInvalidCharactersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apellido paterno debe contener máximo 30 caracteres..
        /// </summary>
        public static string PaternalLastNameMaxLengthMessage {
            get {
                return ResourceManager.GetString("PaternalLastNameMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apellido paterno es obligatorio..
        /// </summary>
        public static string PaternalLastNameRequiredMessage {
            get {
                return ResourceManager.GetString("PaternalLastNameRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        public static string RecoverPasswordButtonConfirm {
            get {
                return ResourceManager.GetString("RecoverPasswordButtonConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a inicio de sesión.
        /// </summary>
        public static string RecoverPasswordButtonGoToLogin {
            get {
                return ResourceManager.GetString("RecoverPasswordButtonGoToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperar contraseña.
        /// </summary>
        public static string RecoverPasswordButtonRecoverPassword {
            get {
                return ResourceManager.GetString("RecoverPasswordButtonRecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al presionar “Recuperar contraseña”, se enviará un código de verificación a la dirección de correo electrónico proporcionada..
        /// </summary>
        public static string RecoverPasswordLabelDescription {
            get {
                return ResourceManager.GetString("RecoverPasswordLabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tu nueva contraseña para continuar.
        /// </summary>
        public static string RecoverPasswordLabelNewPassword {
            get {
                return ResourceManager.GetString("RecoverPasswordLabelNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu contraseña se ha actualizado correctamente, ya puedes iniciar sesión.
        /// </summary>
        public static string RecoverPasswordLabelPasswordUpdated {
            get {
                return ResourceManager.GetString("RecoverPasswordLabelPasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperar Contraseña.
        /// </summary>
        public static string RecoverPasswordLabelTitle {
            get {
                return ResourceManager.GetString("RecoverPasswordLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tus datos para registrarte.
        /// </summary>
        public static string UserSignUpLabelDetails {
            get {
                return ResourceManager.GetString("UserSignUpLabelDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu registro ha sido completado exitosamente. Bienvenido.
        /// </summary>
        public static string UserSignUpLabelRegistrationComplete {
            get {
                return ResourceManager.GetString("UserSignUpLabelRegistrationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de Usuario.
        /// </summary>
        public static string UserSignUpLabelTitle {
            get {
                return ResourceManager.GetString("UserSignUpLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falso Ganador.
        /// </summary>
        public static string WinnerButtonFalseWinner {
            get {
                return ResourceManager.GetString("WinnerButtonFalseWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ganador.
        /// </summary>
        public static string WinnerLabelTitle {
            get {
                return ResourceManager.GetString("WinnerLabelTitle", resourceCulture);
            }
        }
    }
}
