//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Contracts.Faults")]
    [System.SerializableAttribute()]
    public partial class ServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendDto", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class FriendDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FriendIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RequesterIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TargetUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FriendId {
            get {
                return this.FriendIdField;
            }
            set {
                if ((this.FriendIdField.Equals(value) != true)) {
                    this.FriendIdField = value;
                    this.RaisePropertyChanged("FriendId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RequesterId {
            get {
                return this.RequesterIdField;
            }
            set {
                if ((this.RequesterIdField.Equals(value) != true)) {
                    this.RequesterIdField = value;
                    this.RaisePropertyChanged("RequesterId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TargetUserId {
            get {
                return this.TargetUserIdField;
            }
            set {
                if ((this.TargetUserIdField.Equals(value) != true)) {
                    this.TargetUserIdField = value;
                    this.RaisePropertyChanged("TargetUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameSettingsDto", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class GameSettingsDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPrivateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxPlayersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPrivate {
            get {
                return this.IsPrivateField;
            }
            set {
                if ((this.IsPrivateField.Equals(value) != true)) {
                    this.IsPrivateField = value;
                    this.RaisePropertyChanged("IsPrivate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxPlayers {
            get {
                return this.MaxPlayersField;
            }
            set {
                if ((this.MaxPlayersField.Equals(value) != true)) {
                    this.MaxPlayersField = value;
                    this.RaisePropertyChanged("MaxPlayers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LobbyStateDto", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class LobbyStateDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HostNicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LobbyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Lottery.ServiceReference.UserDto[] PlayersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HostNickname {
            get {
                return this.HostNicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.HostNicknameField, value) != true)) {
                    this.HostNicknameField = value;
                    this.RaisePropertyChanged("HostNickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LobbyCode {
            get {
                return this.LobbyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LobbyCodeField, value) != true)) {
                    this.LobbyCodeField = value;
                    this.RaisePropertyChanged("LobbyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Lottery.ServiceReference.UserDto[] Players {
            get {
                return this.PlayersField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayersField, value) != true)) {
                    this.PlayersField = value;
                    this.RaisePropertyChanged("Players");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDto", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class UserDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AvatarIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvatarUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsHostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaternalLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaternalLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> RegistrationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AvatarId {
            get {
                return this.AvatarIdField;
            }
            set {
                if ((this.AvatarIdField.Equals(value) != true)) {
                    this.AvatarIdField = value;
                    this.RaisePropertyChanged("AvatarId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvatarUrl {
            get {
                return this.AvatarUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarUrlField, value) != true)) {
                    this.AvatarUrlField = value;
                    this.RaisePropertyChanged("AvatarUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsHost {
            get {
                return this.IsHostField;
            }
            set {
                if ((this.IsHostField.Equals(value) != true)) {
                    this.IsHostField = value;
                    this.RaisePropertyChanged("IsHost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaternalLastName {
            get {
                return this.MaternalLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MaternalLastNameField, value) != true)) {
                    this.MaternalLastNameField = value;
                    this.RaisePropertyChanged("MaternalLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaternalLastName {
            get {
                return this.PaternalLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PaternalLastNameField, value) != true)) {
                    this.PaternalLastNameField = value;
                    this.RaisePropertyChanged("PaternalLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RegistrationDate {
            get {
                return this.RegistrationDateField;
            }
            set {
                if ((this.RegistrationDateField.Equals(value) != true)) {
                    this.RegistrationDateField = value;
                    this.RaisePropertyChanged("RegistrationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ILotteryService", CallbackContract=typeof(Lottery.ServiceReference.ILotteryServiceCallback))]
    public interface ILotteryService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/SendMessage")]
        void SendMessage(string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/SendMessage")]
        System.Threading.Tasks.Task SendMessageAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/SendRequestFriendship", ReplyAction="http://tempuri.org/IFriendService/SendRequestFriendshipResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lottery.ServiceReference.ServiceFault), Action="http://tempuri.org/IFriendService/SendRequestFriendshipServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Contracts.Faults")]
        void SendRequestFriendship(int currentUserId, int targetUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/SendRequestFriendship", ReplyAction="http://tempuri.org/IFriendService/SendRequestFriendshipResponse")]
        System.Threading.Tasks.Task SendRequestFriendshipAsync(int currentUserId, int targetUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/AcceptFriendRequest", ReplyAction="http://tempuri.org/IFriendService/AcceptFriendRequestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lottery.ServiceReference.ServiceFault), Action="http://tempuri.org/IFriendService/AcceptFriendRequestServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Contracts.Faults")]
        void AcceptFriendRequest(int currentUserId, int requesterId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/AcceptFriendRequest", ReplyAction="http://tempuri.org/IFriendService/AcceptFriendRequestResponse")]
        System.Threading.Tasks.Task AcceptFriendRequestAsync(int currentUserId, int requesterId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/RejectFriendRequest", ReplyAction="http://tempuri.org/IFriendService/RejectFriendRequestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lottery.ServiceReference.ServiceFault), Action="http://tempuri.org/IFriendService/RejectFriendRequestServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Contracts.Faults")]
        void RejectFriendRequest(int currentUserId, int requesterId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/RejectFriendRequest", ReplyAction="http://tempuri.org/IFriendService/RejectFriendRequestResponse")]
        System.Threading.Tasks.Task RejectFriendRequestAsync(int currentUserId, int requesterId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/CancelFriendRequest", ReplyAction="http://tempuri.org/IFriendService/CancelFriendRequestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lottery.ServiceReference.ServiceFault), Action="http://tempuri.org/IFriendService/CancelFriendRequestServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Contracts.Faults")]
        void CancelFriendRequest(int currentUserId, int targetUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/CancelFriendRequest", ReplyAction="http://tempuri.org/IFriendService/CancelFriendRequestResponse")]
        System.Threading.Tasks.Task CancelFriendRequestAsync(int currentUserId, int targetUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/RemoveFriend", ReplyAction="http://tempuri.org/IFriendService/RemoveFriendResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lottery.ServiceReference.ServiceFault), Action="http://tempuri.org/IFriendService/RemoveFriendServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Contracts.Faults")]
        void RemoveFriend(int currentUserId, int friendUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/RemoveFriend", ReplyAction="http://tempuri.org/IFriendService/RemoveFriendResponse")]
        System.Threading.Tasks.Task RemoveFriendAsync(int currentUserId, int friendUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/GetFriends", ReplyAction="http://tempuri.org/IFriendService/GetFriendsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lottery.ServiceReference.ServiceFault), Action="http://tempuri.org/IFriendService/GetFriendsServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Contracts.Faults")]
        Lottery.ServiceReference.FriendDto[] GetFriends(int currentUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/GetFriends", ReplyAction="http://tempuri.org/IFriendService/GetFriendsResponse")]
        System.Threading.Tasks.Task<Lottery.ServiceReference.FriendDto[]> GetFriendsAsync(int currentUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/GetPendingRequests", ReplyAction="http://tempuri.org/IFriendService/GetPendingRequestsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lottery.ServiceReference.ServiceFault), Action="http://tempuri.org/IFriendService/GetPendingRequestsServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Contracts.Faults")]
        Lottery.ServiceReference.FriendDto[] GetPendingRequests(int currentUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/GetPendingRequests", ReplyAction="http://tempuri.org/IFriendService/GetPendingRequestsResponse")]
        System.Threading.Tasks.Task<Lottery.ServiceReference.FriendDto[]> GetPendingRequestsAsync(int currentUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/GetSentRequests", ReplyAction="http://tempuri.org/IFriendService/GetSentRequestsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lottery.ServiceReference.ServiceFault), Action="http://tempuri.org/IFriendService/GetSentRequestsServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Contracts.Faults")]
        Lottery.ServiceReference.FriendDto[] GetSentRequests(int currentUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/GetSentRequests", ReplyAction="http://tempuri.org/IFriendService/GetSentRequestsResponse")]
        System.Threading.Tasks.Task<Lottery.ServiceReference.FriendDto[]> GetSentRequestsAsync(int currentUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/InviteFriendToLobby", ReplyAction="http://tempuri.org/IFriendService/InviteFriendToLobbyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lottery.ServiceReference.ServiceFault), Action="http://tempuri.org/IFriendService/InviteFriendToLobbyServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Contracts.Faults")]
        void InviteFriendToLobby(string lobbyCode, int targetFriendId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/InviteFriendToLobby", ReplyAction="http://tempuri.org/IFriendService/InviteFriendToLobbyResponse")]
        System.Threading.Tasks.Task InviteFriendToLobbyAsync(string lobbyCode, int targetFriendId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/StartGame", ReplyAction="http://tempuri.org/IGameService/StartGameResponse")]
        void StartGame();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/StartGame", ReplyAction="http://tempuri.org/IGameService/StartGameResponse")]
        System.Threading.Tasks.Task StartGameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/UpdateGameSettings", ReplyAction="http://tempuri.org/IGameService/UpdateGameSettingsResponse")]
        void UpdateGameSettings(Lottery.ServiceReference.GameSettingsDto settings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/UpdateGameSettings", ReplyAction="http://tempuri.org/IGameService/UpdateGameSettingsResponse")]
        System.Threading.Tasks.Task UpdateGameSettingsAsync(Lottery.ServiceReference.GameSettingsDto settings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/GetScoreboard", ReplyAction="http://tempuri.org/IGameService/GetScoreboardResponse")]
        void GetScoreboard();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/GetScoreboard", ReplyAction="http://tempuri.org/IGameService/GetScoreboardResponse")]
        System.Threading.Tasks.Task GetScoreboardAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/CreateLobby", ReplyAction="http://tempuri.org/ILobbyService/CreateLobbyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lottery.ServiceReference.ServiceFault), Action="http://tempuri.org/ILobbyService/CreateLobbyServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Contracts.Faults")]
        Lottery.ServiceReference.LobbyStateDto CreateLobby();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/CreateLobby", ReplyAction="http://tempuri.org/ILobbyService/CreateLobbyResponse")]
        System.Threading.Tasks.Task<Lottery.ServiceReference.LobbyStateDto> CreateLobbyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/JoinLobby", ReplyAction="http://tempuri.org/ILobbyService/JoinLobbyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lottery.ServiceReference.ServiceFault), Action="http://tempuri.org/ILobbyService/JoinLobbyServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Contracts.Faults")]
        Lottery.ServiceReference.LobbyStateDto JoinLobby(Lottery.ServiceReference.UserDto currentUser, string lobbyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/JoinLobby", ReplyAction="http://tempuri.org/ILobbyService/JoinLobbyResponse")]
        System.Threading.Tasks.Task<Lottery.ServiceReference.LobbyStateDto> JoinLobbyAsync(Lottery.ServiceReference.UserDto currentUser, string lobbyCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyService/LeaveLobby")]
        void LeaveLobby();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyService/LeaveLobby")]
        System.Threading.Tasks.Task LeaveLobbyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/KickPlayer", ReplyAction="http://tempuri.org/ILobbyService/KickPlayerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lottery.ServiceReference.ServiceFault), Action="http://tempuri.org/ILobbyService/KickPlayerServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Contracts.Faults")]
        void KickPlayer(int targetPlayerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/KickPlayer", ReplyAction="http://tempuri.org/ILobbyService/KickPlayerResponse")]
        System.Threading.Tasks.Task KickPlayerAsync(int targetPlayerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/LoginUser", ReplyAction="http://tempuri.org/IAuthenticationService/LoginUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lottery.ServiceReference.ServiceFault), Action="http://tempuri.org/IAuthenticationService/LoginUserServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Contracts.Faults")]
        Lottery.ServiceReference.UserDto LoginUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/LoginUser", ReplyAction="http://tempuri.org/IAuthenticationService/LoginUserResponse")]
        System.Threading.Tasks.Task<Lottery.ServiceReference.UserDto> LoginUserAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/LogoutUser", ReplyAction="http://tempuri.org/IAuthenticationService/LogoutUserResponse")]
        void LogoutUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/LogoutUser", ReplyAction="http://tempuri.org/IAuthenticationService/LogoutUserResponse")]
        System.Threading.Tasks.Task LogoutUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RequestUserVerification", ReplyAction="http://tempuri.org/IUserService/RequestUserVerificationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lottery.ServiceReference.ServiceFault), Action="http://tempuri.org/IUserService/RequestUserVerificationServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Contracts.Faults")]
        int RequestUserVerification(Lottery.ServiceReference.UserDto userData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RequestUserVerification", ReplyAction="http://tempuri.org/IUserService/RequestUserVerificationResponse")]
        System.Threading.Tasks.Task<int> RequestUserVerificationAsync(Lottery.ServiceReference.UserDto userData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RegisterUser", ReplyAction="http://tempuri.org/IUserService/RegisterUserResponse")]
        int RegisterUser(Lottery.ServiceReference.UserDto userData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RegisterUser", ReplyAction="http://tempuri.org/IUserService/RegisterUserResponse")]
        System.Threading.Tasks.Task<int> RegisterUserAsync(Lottery.ServiceReference.UserDto userData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RegisterGuest", ReplyAction="http://tempuri.org/IUserService/RegisterGuestResponse")]
        int RegisterGuest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RegisterGuest", ReplyAction="http://tempuri.org/IUserService/RegisterGuestResponse")]
        System.Threading.Tasks.Task<int> RegisterGuestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ChangePassword", ReplyAction="http://tempuri.org/IUserService/ChangePasswordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lottery.ServiceReference.ServiceFault), Action="http://tempuri.org/IUserService/ChangePasswordServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Contracts.Faults")]
        bool ChangePassword(int currentUserId, string oldPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ChangePassword", ReplyAction="http://tempuri.org/IUserService/ChangePasswordResponse")]
        System.Threading.Tasks.Task<bool> ChangePasswordAsync(int currentUserId, string oldPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RecoverPassword", ReplyAction="http://tempuri.org/IUserService/RecoverPasswordResponse")]
        void RecoverPassword(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RecoverPassword", ReplyAction="http://tempuri.org/IUserService/RecoverPasswordResponse")]
        System.Threading.Tasks.Task RecoverPasswordAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateProfile", ReplyAction="http://tempuri.org/IUserService/UpdateProfileResponse")]
        System.ValueTuple<bool, string> UpdateProfile(int currentUserId, Lottery.ServiceReference.UserDto userData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateProfile", ReplyAction="http://tempuri.org/IUserService/UpdateProfileResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<bool, string>> UpdateProfileAsync(int currentUserId, Lottery.ServiceReference.UserDto userData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FindUserByNickname", ReplyAction="http://tempuri.org/IUserService/FindUserByNicknameResponse")]
        Lottery.ServiceReference.FriendDto FindUserByNickname(string nickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FindUserByNickname", ReplyAction="http://tempuri.org/IUserService/FindUserByNicknameResponse")]
        System.Threading.Tasks.Task<Lottery.ServiceReference.FriendDto> FindUserByNicknameAsync(string nickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserProfile", ReplyAction="http://tempuri.org/IUserService/GetUserProfileResponse")]
        Lottery.ServiceReference.UserDto GetUserProfile(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserProfile", ReplyAction="http://tempuri.org/IUserService/GetUserProfileResponse")]
        System.Threading.Tasks.Task<Lottery.ServiceReference.UserDto> GetUserProfileAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RequestEmailChange", ReplyAction="http://tempuri.org/IUserService/RequestEmailChangeResponse")]
        bool RequestEmailChange(int userId, string newEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RequestEmailChange", ReplyAction="http://tempuri.org/IUserService/RequestEmailChangeResponse")]
        System.Threading.Tasks.Task<bool> RequestEmailChangeAsync(int userId, string newEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ConfirmEmailChange", ReplyAction="http://tempuri.org/IUserService/ConfirmEmailChangeResponse")]
        bool ConfirmEmailChange(int userId, string newEmail, string verificationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ConfirmEmailChange", ReplyAction="http://tempuri.org/IUserService/ConfirmEmailChangeResponse")]
        System.Threading.Tasks.Task<bool> ConfirmEmailChangeAsync(int userId, string newEmail, string verificationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerificationService/SendVerificationCode", ReplyAction="http://tempuri.org/IVerificationService/SendVerificationCodeResponse")]
        bool SendVerificationCode(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerificationService/SendVerificationCode", ReplyAction="http://tempuri.org/IVerificationService/SendVerificationCodeResponse")]
        System.Threading.Tasks.Task<bool> SendVerificationCodeAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerificationService/VerifyCode", ReplyAction="http://tempuri.org/IVerificationService/VerifyCodeResponse")]
        bool VerifyCode(string email, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerificationService/VerifyCode", ReplyAction="http://tempuri.org/IVerificationService/VerifyCodeResponse")]
        System.Threading.Tasks.Task<bool> VerifyCodeAsync(string email, string code);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILotteryServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILotteryService/NotifyCard")]
        void NotifyCard(int cardId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILotteryService/NotifyWinner")]
        void NotifyWinner(string nickname);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILotteryService/ReceiveChatMessage")]
        void ReceiveChatMessage(string nickname, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILotteryService/PlayerJoined")]
        void PlayerJoined(Lottery.ServiceReference.UserDto newPlayer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILotteryService/PlayerLeft")]
        void PlayerLeft(int playerId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILotteryService/PlayerKicked")]
        void PlayerKicked(int playerId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILotteryService/YouWereKicked")]
        void YouWereKicked();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILotteryService/LobbyClosed")]
        void LobbyClosed();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILotteryService/ReceiveLobbyInvite")]
        void ReceiveLobbyInvite(string inviterNickname, string lobbyCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILotteryServiceChannel : Lottery.ServiceReference.ILotteryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LotteryServiceClient : System.ServiceModel.DuplexClientBase<Lottery.ServiceReference.ILotteryService>, Lottery.ServiceReference.ILotteryService {
        
        public LotteryServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public LotteryServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public LotteryServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LotteryServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LotteryServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SendMessage(string message) {
            base.Channel.SendMessage(message);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(string message) {
            return base.Channel.SendMessageAsync(message);
        }
        
        public void SendRequestFriendship(int currentUserId, int targetUserId) {
            base.Channel.SendRequestFriendship(currentUserId, targetUserId);
        }
        
        public System.Threading.Tasks.Task SendRequestFriendshipAsync(int currentUserId, int targetUserId) {
            return base.Channel.SendRequestFriendshipAsync(currentUserId, targetUserId);
        }
        
        public void AcceptFriendRequest(int currentUserId, int requesterId) {
            base.Channel.AcceptFriendRequest(currentUserId, requesterId);
        }
        
        public System.Threading.Tasks.Task AcceptFriendRequestAsync(int currentUserId, int requesterId) {
            return base.Channel.AcceptFriendRequestAsync(currentUserId, requesterId);
        }
        
        public void RejectFriendRequest(int currentUserId, int requesterId) {
            base.Channel.RejectFriendRequest(currentUserId, requesterId);
        }
        
        public System.Threading.Tasks.Task RejectFriendRequestAsync(int currentUserId, int requesterId) {
            return base.Channel.RejectFriendRequestAsync(currentUserId, requesterId);
        }
        
        public void CancelFriendRequest(int currentUserId, int targetUserId) {
            base.Channel.CancelFriendRequest(currentUserId, targetUserId);
        }
        
        public System.Threading.Tasks.Task CancelFriendRequestAsync(int currentUserId, int targetUserId) {
            return base.Channel.CancelFriendRequestAsync(currentUserId, targetUserId);
        }
        
        public void RemoveFriend(int currentUserId, int friendUserId) {
            base.Channel.RemoveFriend(currentUserId, friendUserId);
        }
        
        public System.Threading.Tasks.Task RemoveFriendAsync(int currentUserId, int friendUserId) {
            return base.Channel.RemoveFriendAsync(currentUserId, friendUserId);
        }
        
        public Lottery.ServiceReference.FriendDto[] GetFriends(int currentUserId) {
            return base.Channel.GetFriends(currentUserId);
        }
        
        public System.Threading.Tasks.Task<Lottery.ServiceReference.FriendDto[]> GetFriendsAsync(int currentUserId) {
            return base.Channel.GetFriendsAsync(currentUserId);
        }
        
        public Lottery.ServiceReference.FriendDto[] GetPendingRequests(int currentUserId) {
            return base.Channel.GetPendingRequests(currentUserId);
        }
        
        public System.Threading.Tasks.Task<Lottery.ServiceReference.FriendDto[]> GetPendingRequestsAsync(int currentUserId) {
            return base.Channel.GetPendingRequestsAsync(currentUserId);
        }
        
        public Lottery.ServiceReference.FriendDto[] GetSentRequests(int currentUserId) {
            return base.Channel.GetSentRequests(currentUserId);
        }
        
        public System.Threading.Tasks.Task<Lottery.ServiceReference.FriendDto[]> GetSentRequestsAsync(int currentUserId) {
            return base.Channel.GetSentRequestsAsync(currentUserId);
        }
        
        public void InviteFriendToLobby(string lobbyCode, int targetFriendId) {
            base.Channel.InviteFriendToLobby(lobbyCode, targetFriendId);
        }
        
        public System.Threading.Tasks.Task InviteFriendToLobbyAsync(string lobbyCode, int targetFriendId) {
            return base.Channel.InviteFriendToLobbyAsync(lobbyCode, targetFriendId);
        }
        
        public void StartGame() {
            base.Channel.StartGame();
        }
        
        public System.Threading.Tasks.Task StartGameAsync() {
            return base.Channel.StartGameAsync();
        }
        
        public void UpdateGameSettings(Lottery.ServiceReference.GameSettingsDto settings) {
            base.Channel.UpdateGameSettings(settings);
        }
        
        public System.Threading.Tasks.Task UpdateGameSettingsAsync(Lottery.ServiceReference.GameSettingsDto settings) {
            return base.Channel.UpdateGameSettingsAsync(settings);
        }
        
        public void GetScoreboard() {
            base.Channel.GetScoreboard();
        }
        
        public System.Threading.Tasks.Task GetScoreboardAsync() {
            return base.Channel.GetScoreboardAsync();
        }
        
        public Lottery.ServiceReference.LobbyStateDto CreateLobby() {
            return base.Channel.CreateLobby();
        }
        
        public System.Threading.Tasks.Task<Lottery.ServiceReference.LobbyStateDto> CreateLobbyAsync() {
            return base.Channel.CreateLobbyAsync();
        }
        
        public Lottery.ServiceReference.LobbyStateDto JoinLobby(Lottery.ServiceReference.UserDto currentUser, string lobbyCode) {
            return base.Channel.JoinLobby(currentUser, lobbyCode);
        }
        
        public System.Threading.Tasks.Task<Lottery.ServiceReference.LobbyStateDto> JoinLobbyAsync(Lottery.ServiceReference.UserDto currentUser, string lobbyCode) {
            return base.Channel.JoinLobbyAsync(currentUser, lobbyCode);
        }
        
        public void LeaveLobby() {
            base.Channel.LeaveLobby();
        }
        
        public System.Threading.Tasks.Task LeaveLobbyAsync() {
            return base.Channel.LeaveLobbyAsync();
        }
        
        public void KickPlayer(int targetPlayerId) {
            base.Channel.KickPlayer(targetPlayerId);
        }
        
        public System.Threading.Tasks.Task KickPlayerAsync(int targetPlayerId) {
            return base.Channel.KickPlayerAsync(targetPlayerId);
        }
        
        public Lottery.ServiceReference.UserDto LoginUser(string username, string password) {
            return base.Channel.LoginUser(username, password);
        }
        
        public System.Threading.Tasks.Task<Lottery.ServiceReference.UserDto> LoginUserAsync(string username, string password) {
            return base.Channel.LoginUserAsync(username, password);
        }
        
        public void LogoutUser() {
            base.Channel.LogoutUser();
        }
        
        public System.Threading.Tasks.Task LogoutUserAsync() {
            return base.Channel.LogoutUserAsync();
        }
        
        public int RequestUserVerification(Lottery.ServiceReference.UserDto userData) {
            return base.Channel.RequestUserVerification(userData);
        }
        
        public System.Threading.Tasks.Task<int> RequestUserVerificationAsync(Lottery.ServiceReference.UserDto userData) {
            return base.Channel.RequestUserVerificationAsync(userData);
        }
        
        public int RegisterUser(Lottery.ServiceReference.UserDto userData) {
            return base.Channel.RegisterUser(userData);
        }
        
        public System.Threading.Tasks.Task<int> RegisterUserAsync(Lottery.ServiceReference.UserDto userData) {
            return base.Channel.RegisterUserAsync(userData);
        }
        
        public int RegisterGuest() {
            return base.Channel.RegisterGuest();
        }
        
        public System.Threading.Tasks.Task<int> RegisterGuestAsync() {
            return base.Channel.RegisterGuestAsync();
        }
        
        public bool ChangePassword(int currentUserId, string oldPassword, string newPassword) {
            return base.Channel.ChangePassword(currentUserId, oldPassword, newPassword);
        }
        
        public System.Threading.Tasks.Task<bool> ChangePasswordAsync(int currentUserId, string oldPassword, string newPassword) {
            return base.Channel.ChangePasswordAsync(currentUserId, oldPassword, newPassword);
        }
        
        public void RecoverPassword(string email) {
            base.Channel.RecoverPassword(email);
        }
        
        public System.Threading.Tasks.Task RecoverPasswordAsync(string email) {
            return base.Channel.RecoverPasswordAsync(email);
        }
        
        public System.ValueTuple<bool, string> UpdateProfile(int currentUserId, Lottery.ServiceReference.UserDto userData) {
            return base.Channel.UpdateProfile(currentUserId, userData);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<bool, string>> UpdateProfileAsync(int currentUserId, Lottery.ServiceReference.UserDto userData) {
            return base.Channel.UpdateProfileAsync(currentUserId, userData);
        }
        
        public Lottery.ServiceReference.FriendDto FindUserByNickname(string nickname) {
            return base.Channel.FindUserByNickname(nickname);
        }
        
        public System.Threading.Tasks.Task<Lottery.ServiceReference.FriendDto> FindUserByNicknameAsync(string nickname) {
            return base.Channel.FindUserByNicknameAsync(nickname);
        }
        
        public Lottery.ServiceReference.UserDto GetUserProfile(int userId) {
            return base.Channel.GetUserProfile(userId);
        }
        
        public System.Threading.Tasks.Task<Lottery.ServiceReference.UserDto> GetUserProfileAsync(int userId) {
            return base.Channel.GetUserProfileAsync(userId);
        }
        
        public bool RequestEmailChange(int userId, string newEmail) {
            return base.Channel.RequestEmailChange(userId, newEmail);
        }
        
        public System.Threading.Tasks.Task<bool> RequestEmailChangeAsync(int userId, string newEmail) {
            return base.Channel.RequestEmailChangeAsync(userId, newEmail);
        }
        
        public bool ConfirmEmailChange(int userId, string newEmail, string verificationCode) {
            return base.Channel.ConfirmEmailChange(userId, newEmail, verificationCode);
        }
        
        public System.Threading.Tasks.Task<bool> ConfirmEmailChangeAsync(int userId, string newEmail, string verificationCode) {
            return base.Channel.ConfirmEmailChangeAsync(userId, newEmail, verificationCode);
        }
        
        public bool SendVerificationCode(string email) {
            return base.Channel.SendVerificationCode(email);
        }
        
        public System.Threading.Tasks.Task<bool> SendVerificationCodeAsync(string email) {
            return base.Channel.SendVerificationCodeAsync(email);
        }
        
        public bool VerifyCode(string email, string code) {
            return base.Channel.VerifyCode(email, code);
        }
        
        public System.Threading.Tasks.Task<bool> VerifyCodeAsync(string email, string code) {
            return base.Channel.VerifyCodeAsync(email, code);
        }
    }
}
